import { Geist, Geist_Mono } from "next/font/google";
import "flowbite/dist/flowbite.min.css";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import ReduxProvider from "@/redux/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-white">
        <ReduxProvider>
          <div className="container mx-auto my-8">
            <Header/>
            {children}
          </div>
          <Footer/>
        </ReduxProvider>
      </body>
    </html>
  );
}
